include: package:lint/analysis_options.yaml

analyzer:
  exclude: [
    lib/app/service_locator.dart,
    lib/app/app.router.dart,
    lib/ui/**.form.dart,
    lib/generated_plugin_registrant.dart,
  ]

linter:
  rules:
    - lines_longer_than_80_chars
    - always_use_package_imports
    # - package_api_docs
    # - public_member_api_docs

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 10
    lines-of-executable-code: 1000
    number-of-arguments: 6
  metrics-exclude:
    - test/**
