name: pronto_mia
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  date_time_picker: ^2.0.0
  file_picker: ^3.0.1
  firebase_core:
  firebase_messaging:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^2.0.0
  flutter_pdfview: ^1.1.0
  flutter_secure_storage:
  flutter_svg:
  global_configuration: ^1.6.0
  graphql:
  http:
  http_parser:
  image_picker:
  intl: ^0.17.0
  jdenticon_dart:
  jwt_decoder:
  logging:
  responsive_builder:
  shared_preferences:
  stacked:
  stacked_services:
  universal_html:
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner:
  flutter_native_splash:
  flutter_test:
    sdk: flutter
  lint:
  mockito:
  stacked_generator:

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/3.0x/pronto_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/pronto_logo.png
    - assets/images/1.5x/pronto_logo.png
    - assets/images/2.0x/pronto_logo.png
    - assets/images/2.5x/pronto_logo.png
    - assets/images/3.0x/pronto_logo.png
    - assets/images/pronto_icon.png
    - assets/images/1.5x/pronto_icon.png
    - assets/images/2.0x/pronto_icon.png
    - assets/images/2.5x/pronto_icon.png
    - assets/images/3.0x/pronto_icon.png
    - assets/cfg/app_settings.json
    - assets/cfg/app_settings_dev.json
    - assets/cfg/app_settings_prod.json

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
