name: pronto_mia
description: A new Flutter application.

publish_to: 'none'

version: 0.5.0+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  chewie: ^1.2.2
  date_time_picker: ^2.0.0
  file_picker: ^4.1.4
  firebase_core: ^1.1.0
  firebase_messaging: ^10.0.8
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.1.0
  flutter_secure_storage: ^4.0.0
  flutter_svg: ^0.23.0+1 # ^0.22.0 depends on http ^0.13.0
  global_configuration: ^2.0.0-nullsafety.1
  graphql: ^5.0.0
  http: ^0.13.4 # ^0.13.0 incompatible with graphql any
  http_parser: ^4.0.0 # ^4.0.0 depends on http ^0.13.0
  intl: ^0.17.0
  jdenticon_dart: ^2.0.0 # ^2.0.0 incompatible with http ^0.12.0
  jwt_decoder: ^2.0.0
  logging: ^1.0.0
  mailer: ^5.0.2
  multi_select_flutter: ^4.0.0
  responsive_builder: ^0.4.0
  shared_preferences: ^2.0.0
  stacked: ^2.2.7
  stacked_services: ^0.8.0
  universal_html: ^2.0.8 # ^2.0.0 incompatible with http ^0.12.0
  url_launcher: ^6.0.0
  video_player: ^2.2.7

dev_dependencies:
  build_runner:
  dart_code_metrics:
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter
  lint: ^1.5.0
  mockito: ^5.0.16 # ^5.0.0 depends on http ^0.13.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/3.0x/pronto_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/pronto_logo.png
    - assets/images/1.5x/pronto_logo.png
    - assets/images/2.0x/pronto_logo.png
    - assets/images/2.5x/pronto_logo.png
    - assets/images/3.0x/pronto_logo.png
    - assets/images/pronto_icon.png
    - assets/images/1.5x/pronto_icon.png
    - assets/images/2.0x/pronto_icon.png
    - assets/images/2.5x/pronto_icon.png
    - assets/images/3.0x/pronto_icon.png
    - assets/cfg/app_settings.json
    - assets/cfg/app_settings_dev.json
    - assets/cfg/app_settings_prod.json
    - assets/cfg/mailer_credentials.json
