name: pronto_mia
description: A new Flutter application.

publish_to: 'none'

version: 0.3.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  date_time_picker: ^2.0.0
  file_picker: ^3.0.0
  firebase_core: ^1.1.0
  firebase_messaging: ^9.1.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.1.0
  flutter_secure_storage: ^4.0.0
  flutter_svg: ^0.19.0 # ^0.22.0 depends on http ^0.13.0
  global_configuration: ^1.6.0
  graphql: ^4.0.0
  http: ^0.12.0 # ^0.13.0 incompatible with graphql any
  http_parser: ^3.1.0 # ^4.0.0 depends on http ^0.13.0
  intl: ^0.17.0
  jdenticon_dart: ^1.2.0 # ^2.0.0 incompatible with http ^0.12.0
  jwt_decoder: ^2.0.0
  logging: ^1.0.0
  responsive_builder: ^0.4.0
  shared_preferences: ^2.0.0
  stacked: ^1.9.0
  stacked_services: ^0.8.0
  universal_html: ^1.2.0 # ^2.0.0 incompatible with http ^0.12.0
  url_launcher: ^6.0.0

dev_dependencies:
  build_runner:
  flutter_native_splash: ^0.3.0
  flutter_test:
    sdk: flutter
  lint: ^1.5.0
  mockito: ^4.1.0 # ^5.0.0 depends on http ^0.13.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/3.0x/pronto_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/pronto_logo.png
    - assets/images/1.5x/pronto_logo.png
    - assets/images/2.0x/pronto_logo.png
    - assets/images/2.5x/pronto_logo.png
    - assets/images/3.0x/pronto_logo.png
    - assets/images/pronto_icon.png
    - assets/images/1.5x/pronto_icon.png
    - assets/images/2.0x/pronto_icon.png
    - assets/images/2.5x/pronto_icon.png
    - assets/images/3.0x/pronto_icon.png
    - assets/cfg/app_settings.json
    - assets/cfg/app_settings_dev.json
    - assets/cfg/app_settings_prod.json
