# This is a basic workflow to help you get started with Actions

name: App CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
        
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.pub-cache/hosted/pub.dartlang.org
        key: ${{ runner.os }}-pub-${{ hashFiles('pubspeck.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-
          
    - name: Cache generated source files
      uses: actions/cache@v2
      with:
        path: lib/app/
        key: ${{ runner.os }}-stacked-${{ hashFiles('lib/app/app.dart') }}
        restore-keys: |
          ${{ runner.os }}-stacked-
          
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate additional source files
      run: flutter pub run build_runner build --delete-conflicting-outputs
          
    - name: Check code format
      run: flutter format --set-exit-if-changed .
      
    - name: Check linter rules
      run: flutter analyze
    
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
        
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.pub-cache/hosted/pub.dartlang.org
        key: ${{ runner.os }}-pub-${{ hashFiles('pubspeck.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-
          
    - name: Cache generated source files
      uses: actions/cache@v2
      with:
        path: lib/app/
        key: ${{ runner.os }}-stacked-${{ hashFiles('lib/app/app.dart') }}
        restore-keys: |
          ${{ runner.os }}-stacked-
      
    - name: Run tests
      run: flutter test --coverage
    
    - name: Install lcov
      run: sudo apt-get install lcov -y
    
    - name: Generate test coverage
      run: genhtml coverage/lcov.info -o coverage/html
    
    - name: Upload test coverage
      uses: actions/upload-artifact@v1
      with:
        name: test-coverage
        path: coverage/
        
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
        
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.pub-cache/hosted/pub.dartlang.org
        key: ${{ runner.os }}-pub-${{ hashFiles('pubspeck.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-
          
    - name: Cache generated source files
      uses: actions/cache@v2
      with:
        path: lib/app/
        key: ${{ runner.os }}-stacked-${{ hashFiles('lib/app/app.dart') }}
        restore-keys: |
          ${{ runner.os }}-stacked-
      
    - name: Build for android
      run: flutter build apk
      
    - name: Upload android build
      # if: startsWith(github.refs, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/apk/release/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  documentation:
    # if: startsWith(github.refs, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
        
    - name: Enable dartdoc
      run: flutter pub global activate dartdoc
      
    - name: Generate code documentation
      run: flutter pub global run dartdoc:dartdoc
    
    - name: Upload code documentation
      uses: softprops/action-gh-release@v1
      with:
        files: doc/api/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
