# This is a basic workflow to help you get started with Actions

name: App CI

on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
    - name: Check code format
      run: flutter format --set-exit-if-changed .
    - name: Install dependencies
      run: flutter pub get
    - name: Generate additional source files
      run: flutter pub run build_runner build --delete-conflicting-outputs
    - name: Check linter rules
      run: flutter analyze
    
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
    - run: flutter pub get
    - run: flutter pub run build_runner build --delete-conflicting-outputs
    - run: flutter test --coverage
    - run: sudo apt-get install lcov -y
    - run: genhtml coverage/lcov.info -o coverage/html
    - uses: actions/upload-artifact@v1
      with:
        name: code-coverage
        path: coverage/
        
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.3'
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
          
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.3'
      - run: flutter pub global activate dartdoc
      - run: flutter pub global run dartdoc:dartdoc
      - uses: actions/upload-artifact@v1
        with:
          name: code-documentation
          path: doc/api/  
          
