name: App CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
        
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: ~/.pub-cache/hosted/pub.dartlang.org
        key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: Cache generated source files
      id: cache-generated-source
      uses: actions/cache@v2
      with:
        path: lib/app/
        key: ${{ runner.os }}-stacked-${{ hashFiles('lib/app/app.dart') }}
          
    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: flutter pub get
      
    - name: Generate additional source files
      if: steps.cache-generated-source.outputs.cache-hit != 'true'
      run: flutter pub run build_runner build --delete-conflicting-outputs
          
    - name: Check code format
      run: flutter format --set-exit-if-changed .
      
    - name: Check linter rules
      run: flutter analyze
    
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
        
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: ~/.pub-cache/hosted/pub.dartlang.org
        key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-
          
    - name: Cache generated source files
      id: cache-generated-source
      uses: actions/cache@v2
      with:
        path: lib/app/
        key: ${{ runner.os }}-stacked-${{ hashFiles('lib/app/app.dart') }}

    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: flutter pub get
      
    - name: Generate additional source files
      if: steps.cache-generated-source.outputs.cache-hit != 'true'
      run: flutter pub run build_runner build --delete-conflicting-outputs
      
    - name: Run tests
      run: flutter test --coverage
    
    - name: Install lcov
      run: sudo apt-get install lcov -y
    
    - name: Generate test coverage
      run: genhtml coverage/lcov.info -o coverage/html
    
    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      with:
        name: test-coverage
        path: coverage/
        retention-days: 2
        
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
        
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.pub-cache/hosted/pub.dartlang.org
        key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-
          
    - name: Cache generated source files
      uses: actions/cache@v2
      with:
        path: lib/app/
        key: ${{ runner.os }}-stacked-${{ hashFiles('lib/app/app.dart') }}
        restore-keys: |
          ${{ runner.os }}-stacked-
      
    - name: Build for android
      run: flutter build apk

    - name: Upload android build
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v2
      with:
        name: android-build
        path: build/app/outputs/apk/release/app-release.apk
        retention-days: 1
      
  documentation:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'

    - name: Enable dartdoc
      run: flutter pub global activate dartdoc
      
    - name: Generate code documentation
      run: flutter pub global run dartdoc:dartdoc

    - name: Upload code documentation
      uses: actions/upload-artifact@v2
      with:
        name: code-documentation
        path: doc/api
        retention-days: 1
          
  release:
    runs-on: ubuntu-latest
    needs: [test, build, documentation]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts/

    - name: Check working directory
      run: ls -R
    
    - name: Upload release files
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md
        files: |
          artifacts/test-coverage/
          artifacts/android-build/app-release.apk
          artifacts/code-documentation/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
